// ReSharper disable UseRawString
// ReSharper disable InconsistentNaming

namespace All_Decks.Classes.Constants;

public static partial class Statements
{
    public const string InsertCards = 
        @"INSERT INTO cards (
	""artist"",
	""artistIds"",
	""asciiName"",
	""attractionLights"",
	""availability"",
	""boosterTypes"",
	""borderColor"",
	""cardParts"",
	""colorIdentity"",
	""colorIndicator"",
	""colors"",
	""count"",
	""defense"",
	""duelDeck"",
	""edhrecRank"",
	""edhrecSaltiness"",
	""faceConvertedManaCost"",
	""faceFlavorName"",
	""faceManaValue"",
	""faceName"",
	""fileName"",
	""finishes"",
	""flavorName"",
	""flavorText"",
	""frameEffects"",
	""frameVersion"",
	""hand"",
	""hasAlternativeDeckLimit"",
	""hasContentWarning"",
	""hasFoil"",
	""hasNonFoil"",
	""isAlternative"",
	""isCommander"",
	""isFoil"",
	""isFullArt"",
	""isFunny"",
	""isMainBoard"",
	""isOnlineOnly"",
	""isOversized"",
	""isPromo"",
	""isRebalanced"",
	""isReprint"",
	""isReserved"",
	""isSideBoard"",
	""isStarter"",
	""isStorySpotlight"",
	""isTextless"",
	""isTimeshifted"",
	""keywords"",
	""language"",
	""layout"",
	""leadershipSkills"",
	""life"",
	""loyalty"",
	""manaCost"",
	""manaValue"",
	""name"",
	""number"",
	""originalPrintings"",
	""originalReleaseDate"",
	""originalText"",
	""originalType"",
	""otherFaceIds"",
	""power"",
	""printings"",
	""promoTypes"",
	""rarity"",
	""rebalancedPrintings"",
	""relatedCards"",
	""securityStamp"",
	""setCode"",
	""side"",
	""signature"",
	""sourceProducts"",
	""subsets"",
	""subtypes"",
	""supertypes"",
	""text"",
	""toughness"",
	""type"",
	""types"",
	""uuid"",
	""variations"",
	""watermark""
) VALUES (
";
}